# Generated by Django 5.0.7 on 2024-08-08 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_remove_course_students_course_student'),
        ('User', '0008_user_education_user_last_login_user_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='User.user'),
        ),
    ]
