# Generated by Django 5.1 on 2024-08-20 09:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quize', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('SA', 'Short Answer'), ('MCQ', 'Multiple Choice Question'), ('TF', 'True/False'), ('FIB', 'Fill in the Blanks'), ('ESSAY', 'Essay'), ('MATCH', 'Matching')], max_length=6)),
                ('marks', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quize.quiz')),
            ],
        ),
    ]
